name: Test and Deploy Lib and FastAPI Service

on:
  push:
    branches:
      - main
      - master # --> S칩 rode este scripts nas branch main e master

permissions:
  contents: read
  packages: write # --> Permiss칫es para criar os arquivos libs e rodar

jobs: # --> tarefas a fazer
  test-lib:
    name: 游빍 Test Calculator Lib
    runs-on: ubuntu-latest # --> m치quina virtual que ser치 rodado.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # --> baixa os c칩digos (libs install) para a m치quina virtual conseguir rodar o test

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build and test tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine pytest

      - name: Install lib locally
        run: |
          python -m pip install .

      - name: Run tests for library
        run: |
          pytest test_lib/
  
  deploy-lib:
    name: 游닍 Publish Calculator Lib to GitHub Packages
    runs-on: ubuntu-latest
    needs: test-lib

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine

      - name: Build library
        run: |
          python -m build
      
      - name: Publish library to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          python -m build
          twine upload dist/*