name: Test and Deploy Lib and FastAPI Service

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  packages: write

jobs:
  test-lib:
    name: 🧪 Test Calculator Lib
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build and test tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine pytest

      - name: Install lib locally
        run: |
          python -m pip install .

      - name: Run tests for library
        run: |
          pytest test_lib/